run:
  timeout: 60m
  go: 1.17

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow
