name: Bug Report
description: Report a bug in the gcorelabscloud-go SDK
title: "[BUG] ..."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much information as possible to help us reproduce and fix the issue.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check these boxes before submitting the issue
      options:
      - label: I have searched existing issues to avoid creating duplicates
        required: true
      - label: I am using the latest version of the SDK
        required: true

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: What version of Go are you using?
      placeholder: go version go1.22.0 darwin/arm64
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go Environment
      description: Please run `go env` and paste the output
      render: shell
    validations:
      required: true

  - type: textarea
    id: sdk-version
    attributes:
      label: SDK Version & Installation Method
      description: How did you install the SDK and which version are you using?
      placeholder: |
        go get github.com/G-Core/gcorelabscloud-go@v0.x.x
        # or
        go.mod dependency version: v0.x.x
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: |
        Describe what you were trying to do and what happened instead.
        Include any error messages or stack traces if available.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Please provide a minimal code example that reproduces the issue.
        Redact any sensitive information (API keys, credentials, etc).
      placeholder: |
        ```go
        package main

        func main() {
            // Your example code here
        }
        ```
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem that might be helpful?
      placeholder: |
        - Are you using any specific GCore services?
        - Any specific configuration or environment setup?
        - Screenshots if applicable 