name: build

on:
  push:
    branches: [ master, main, test-artifacts-upload ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcoreclient
          path: gcoreclient
