name: build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build darwin/arm64
        run: make build-with-dist GOOS=darwin GOARCH=arm64

      - name: Build windows/amd64
        run: make build-with-dist GOOS=windows GOARCH=amd64

      - name: Set truncated SHA
        id: truncated_sha
        run: echo "github_short_sha=${GITHUB_SHA::8}" >> "${GITHUB_OUTPUT}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcoreclient-${{ steps.truncated_sha.github_short_sha }}
          path: gcoreclient*
